# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05dbc7fc20f95bf2735629ac8c955d1aa0a51890cf96de9c601ce7f2e3d78027e1d153400d16c7eb66335fdb0118319b24d3572f25a6e5c7f498f36e66629434

test:
  secret_key_base: 962447898ebbe2a04edb14a25e122812acc6e98c4b6092b3487bc2facc2fe8d6baf8b98598836d254ffdfb5a13b648ec07499d18926e69ffd4cd6c603be88d72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
